// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _2026_campus_room_booking_backend.Data;

#nullable disable

namespace _2026_campus_room_booking_backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260213234517_AddPasswordToUsers")]
    partial class AddPasswordToUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("_2026_campus_room_booking_backend.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Role");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@campus.local",
                            FullName = "Admin User",
                            IsDeleted = false,
                            Password = "$2a$11$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5YmMxSUaqzpva",
                            Role = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student@campus.local",
                            FullName = "Student User",
                            IsDeleted = false,
                            Password = "$2a$11$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5YmMxSUaqzpva",
                            Role = 0
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "dosen@campus.local",
                            FullName = "Dosen Pembimbing",
                            IsDeleted = false,
                            Password = "$2a$11$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5YmMxSUaqzpva",
                            Role = 0
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "staff@campus.local",
                            FullName = "Staff Akademik",
                            IsDeleted = false,
                            Password = "$2a$11$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5YmMxSUaqzpva",
                            Role = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mahasiswa.if@campus.local",
                            FullName = "Mahasiswa Informatika",
                            IsDeleted = false,
                            Password = "$2a$11$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5YmMxSUaqzpva",
                            Role = 0
                        });
                });

            modelBuilder.Entity("_2026_campus_room_booking_backend.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Building")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Floor")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Status");

                    b.HasIndex("Building", "Floor");

                    b.ToTable("Rooms", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Building = "Gedung D4",
                            Capacity = 40,
                            Category = "Classroom",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ruang kelas baris A lantai 3, dilengkapi proyektor",
                            Floor = 3,
                            IsDeleted = false,
                            Name = "A 301",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            Building = "Gedung D4",
                            Capacity = 40,
                            Category = "Classroom",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ruang kelas baris A lantai 3",
                            Floor = 3,
                            IsDeleted = false,
                            Name = "A 302",
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            Building = "Gedung D4",
                            Capacity = 35,
                            Category = "Classroom",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ruang kelas baris B lantai 2",
                            Floor = 2,
                            IsDeleted = false,
                            Name = "B 201",
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            Building = "Gedung D4",
                            Capacity = 30,
                            Category = "Lab",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lab komputer baris C lantai 4",
                            Floor = 4,
                            IsDeleted = false,
                            Name = "C 401",
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            Building = "Gedung D4",
                            Capacity = 120,
                            Category = "Lecture Hall",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Aula besar lantai 1 gedung D4",
                            Floor = 1,
                            IsDeleted = false,
                            Name = "A 101",
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            Building = "Gedung D3",
                            Capacity = 40,
                            Category = "Classroom",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ruang kelas gedung D3 lantai 3",
                            Floor = 3,
                            IsDeleted = false,
                            Name = "HH 301",
                            Status = 0
                        },
                        new
                        {
                            Id = 7,
                            Building = "Gedung D3",
                            Capacity = 40,
                            Category = "Classroom",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ruang kelas gedung D3 lantai 3",
                            Floor = 3,
                            IsDeleted = false,
                            Name = "HH 302",
                            Status = 0
                        },
                        new
                        {
                            Id = 8,
                            Building = "Gedung D3",
                            Capacity = 30,
                            Category = "Lab",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lab komputer gedung D3 lantai 2",
                            Floor = 2,
                            IsDeleted = false,
                            Name = "HH 201",
                            Status = 0
                        },
                        new
                        {
                            Id = 9,
                            Building = "Gedung D3",
                            Capacity = 50,
                            Category = "Seminar Room",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ruang seminar gedung D3 lantai 1",
                            Floor = 1,
                            IsDeleted = false,
                            Name = "HH 102",
                            Status = 0
                        },
                        new
                        {
                            Id = 10,
                            Building = "Gedung SAW",
                            Capacity = 45,
                            Category = "Classroom",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ruang kelas gedung SAW lantai 10 ruang 08",
                            Floor = 10,
                            IsDeleted = false,
                            Name = "SAW 10.08",
                            Status = 0
                        },
                        new
                        {
                            Id = 11,
                            Building = "Gedung SAW",
                            Capacity = 45,
                            Category = "Classroom",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ruang kelas gedung SAW lantai 10 ruang 09",
                            Floor = 10,
                            IsDeleted = false,
                            Name = "SAW 10.09",
                            Status = 0
                        },
                        new
                        {
                            Id = 12,
                            Building = "Gedung SAW",
                            Capacity = 30,
                            Category = "Lab",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lab gedung SAW lantai 5 ruang 01",
                            Floor = 5,
                            IsDeleted = false,
                            Name = "SAW 5.01",
                            Status = 0
                        },
                        new
                        {
                            Id = 13,
                            Building = "Gedung SAW",
                            Capacity = 60,
                            Category = "Seminar Room",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ruang seminar gedung SAW lantai 3 ruang 05",
                            Floor = 3,
                            IsDeleted = false,
                            Name = "SAW 3.05",
                            Status = 0
                        },
                        new
                        {
                            Id = 14,
                            Building = "Gedung PascaSarjana",
                            Capacity = 25,
                            Category = "Meeting Room",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ruang meeting PascaSarjana lantai 7 ruang 01",
                            Floor = 7,
                            IsDeleted = false,
                            Name = "PS 7.01",
                            Status = 0
                        },
                        new
                        {
                            Id = 15,
                            Building = "Gedung PascaSarjana",
                            Capacity = 35,
                            Category = "Classroom",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ruang kelas PascaSarjana lantai 7 ruang 02",
                            Floor = 7,
                            IsDeleted = false,
                            Name = "PS 7.02",
                            Status = 0
                        });
                });

            modelBuilder.Entity("_2026_campus_room_booking_backend.Models.RoomBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BookedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Purpose")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("StartTime");

                    b.HasIndex("Status");

                    b.ToTable("RoomBookings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
